# Generated by Django 4.1.1 on 2022-12-19 14:50

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ("HTMS_App", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="NewIncidentCategory",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("category_name", models.CharField(max_length=100, null=True)),
                ("subcategory_name", models.CharField(max_length=100, null=True)),
            ],
        ),
        migrations.CreateModel(
            name="NewIncidentMode",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("mode_name", models.CharField(max_length=100, null=True)),
            ],
        ),
        migrations.CreateModel(
            name="NewIncidentPriority",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("priority_name", models.CharField(max_length=100, null=True)),
            ],
        ),
        migrations.CreateModel(
            name="NewIncidentRequestType",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("request_name", models.CharField(max_length=100, null=True)),
            ],
        ),
        migrations.CreateModel(
            name="NewIncidentStatus",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("status_name", models.CharField(max_length=100, null=True)),
            ],
        ),
        migrations.CreateModel(
            name="Requests",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("requester_name", models.CharField(max_length=100, null=True)),
                ("requester_pr_number", models.CharField(max_length=100, null=True)),
                ("requester_designation", models.CharField(max_length=100, null=True)),
                ("requester_department", models.CharField(max_length=100, null=True)),
                ("requester_email", models.CharField(max_length=100, null=True)),
                ("requester_extension", models.CharField(max_length=100, null=True)),
                ("requester_phone_number", models.CharField(max_length=100, null=True)),
                ("request_type", models.CharField(max_length=100, null=True)),
                ("request_status", models.CharField(max_length=100, null=True)),
                ("request_mode", models.CharField(max_length=100, null=True)),
                ("request_priority", models.CharField(max_length=100, null=True)),
                ("request_category", models.CharField(max_length=100, null=True)),
                ("subject", models.CharField(max_length=100, null=True)),
                ("description", models.TextField(max_length=99999999, null=True)),
                ("request_creation_date", models.DateTimeField(auto_now_add=True)),
                (
                    "request_completion_date",
                    models.DateTimeField(blank=True, null=True),
                ),
                ("last_modified_date", models.DateTimeField(auto_now_add=True)),
                (
                    "last_modified_by",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="updater",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "request_submitter",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="creator",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "request_technician",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="assignee",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "ordering": ["-id"],
            },
        ),
        migrations.CreateModel(
            name="Technician",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("department", models.CharField(max_length=100, null=True)),
                ("designation", models.CharField(max_length=100, null=True)),
                ("pr_number", models.CharField(max_length=100, null=True)),
                (
                    "gender",
                    models.CharField(
                        choices=[("Male", "Male"), ("Female", "Female")], max_length=6
                    ),
                ),
                ("facility", models.ManyToManyField(to="HTMS_App.facilitydropdown")),
                (
                    "user",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
        ),
        migrations.DeleteModel(
            name="Employee",
        ),
    ]
