# Generated by Django 4.1.1 on 2023-01-17 18:32

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("HTMS_App", "0002_assest_details_assets_newincidentcategory_and_more"),
    ]

    operations = [
        migrations.DeleteModel(
            name="Assest_Details",
        ),
    ]
