# Generated by Django 4.1.1 on 2022-12-19 14:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("HTMS_App", "0002_newincidentcategory_newincidentmode_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="technician",
            name="mobile_number",
            field=models.CharField(default=0, max_length=10),
            preserve_default=False,
        ),
    ]
