# Generated by Django 4.1.1 on 2023-01-17 18:45

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ("HTMS_App", "0003_delete_assest_details"),
    ]

    operations = [
        migrations.CreateModel(
            name="Assest_Details",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("brand", models.CharField(db_index=True, max_length=100, null=True)),
                (
                    "model_name",
                    models.CharField(db_index=True, max_length=100, null=True),
                ),
                (
                    "model_number",
                    models.CharField(db_index=True, max_length=100, null=True),
                ),
                (
                    "serial_number",
                    models.CharField(db_index=True, max_length=100, null=True),
                ),
                (
                    "date_of_purchase",
                    models.DateTimeField(auto_now_add=True, db_index=True),
                ),
                ("date_added", models.DateTimeField(auto_now_add=True, db_index=True)),
                (
                    "current_status",
                    models.CharField(
                        choices=[
                            ("in-stock", "In Stock"),
                            ("in-use", "In Use"),
                            ("returned_to_vendor", "Returned To Vendor"),
                            ("lost", "Lost"),
                        ],
                        db_index=True,
                        default="in-stock",
                        max_length=20,
                    ),
                ),
                (
                    "description",
                    models.TextField(db_index=True, max_length=99999999, null=True),
                ),
                (
                    "assest_name",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="assest_details",
                        to="HTMS_App.assets",
                    ),
                ),
                (
                    "assest_user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="users",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "assign_to_ticket",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="assign_to_ticket",
                        to="HTMS_App.requests",
                    ),
                ),
                (
                    "facility",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="facilities",
                        to="HTMS_App.facilitydropdown",
                    ),
                ),
            ],
        ),
    ]
