# Generated by Django 4.1.1 on 2022-12-27 16:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("HTMS_App", "0005_alter_technician_mobile_number_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="technician",
            name="mobile_number",
            field=models.CharField(max_length=10),
        ),
        migrations.AlterField(
            model_name="technician",
            name="pr_number",
            field=models.CharField(max_length=100, null=True),
        ),
    ]
