# Generated by Django 4.1.1 on 2023-01-23 15:29

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ("HTMS_App", "0005_asset_details_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="asset_details",
            name="current_status",
            field=models.CharField(
                choices=[
                    ("in_stock", "In Stock"),
                    ("in_use", "In Use"),
                    ("returned_to_vendor", "Returned To Vendor"),
                    ("lost", "Lost"),
                ],
                db_index=True,
                default="in-stock",
                max_length=20,
            ),
        ),
        migrations.AlterField(
            model_name="technician",
            name="user",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL
            ),
        ),
    ]
