# Generated by Django 4.1.1 on 2022-12-29 12:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("HTMS_App", "0006_alter_technician_mobile_number_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="technician",
            name="extension_number",
            field=models.CharField(max_length=10, null=True),
        ),
    ]
