# Generated by Django 4.1.1 on 2023-01-25 15:38

from django.conf import settings
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ("HTMS_App", "0007_alter_technician_user"),
    ]

    operations = [
        migrations.RenameModel(
            old_name="Asset_Details",
            new_name="AssetDetails",
        ),
    ]
