# Generated by Django 4.1.1 on 2022-12-30 12:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("HTMS_App", "0007_technician_extension_number"),
    ]

    operations = [
        migrations.AlterField(
            model_name="technician",
            name="department",
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name="technician",
            name="designation",
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name="technician",
            name="extension_number",
            field=models.CharField(blank=True, max_length=10, null=True),
        ),
        migrations.AlterField(
            model_name="technician",
            name="mobile_number",
            field=models.CharField(blank=True, max_length=10, null=True),
        ),
        migrations.AlterField(
            model_name="technician",
            name="pr_number",
            field=models.CharField(default="", max_length=100),
            preserve_default=False,
        ),
    ]
