# Generated by Django 4.1.1 on 2023-01-16 16:54

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ("HTMS_App", "0008_alter_technician_department_and_more"),
    ]

    operations = [
        migrations.CreateModel(
            name="Assets",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "assest_name",
                    models.CharField(db_index=True, max_length=100, unique=True),
                ),
                (
                    "assest_type",
                    models.CharField(db_index=True, max_length=100, null=True),
                ),
            ],
        ),
        migrations.AlterField(
            model_name="facilitydropdown",
            name="facility_code",
            field=models.CharField(db_index=True, max_length=255),
        ),
        migrations.AlterField(
            model_name="facilitydropdown",
            name="facility_name",
            field=models.CharField(db_index=True, max_length=255),
        ),
        migrations.AlterField(
            model_name="newincidentcategory",
            name="category_name",
            field=models.CharField(db_index=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name="newincidentcategory",
            name="subcategory_name",
            field=models.CharField(db_index=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name="newincidentmode",
            name="mode_name",
            field=models.CharField(db_index=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name="newincidentpriority",
            name="priority_name",
            field=models.CharField(db_index=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name="newincidentrequesttype",
            name="request_name",
            field=models.CharField(db_index=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name="newincidentstatus",
            name="status_name",
            field=models.CharField(db_index=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name="requests",
            name="description",
            field=models.TextField(db_index=True, max_length=99999999, null=True),
        ),
        migrations.AlterField(
            model_name="requests",
            name="last_modified_date",
            field=models.DateTimeField(auto_now_add=True, db_index=True),
        ),
        migrations.AlterField(
            model_name="requests",
            name="request_assigned_time",
            field=models.DateTimeField(blank=True, db_index=True, null=True),
        ),
        migrations.AlterField(
            model_name="requests",
            name="request_category",
            field=models.CharField(db_index=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name="requests",
            name="request_closed_time",
            field=models.DateTimeField(blank=True, db_index=True, null=True),
        ),
        migrations.AlterField(
            model_name="requests",
            name="request_completion_date",
            field=models.DateTimeField(blank=True, db_index=True, null=True),
        ),
        migrations.AlterField(
            model_name="requests",
            name="request_creation_date",
            field=models.DateTimeField(auto_now_add=True, db_index=True),
        ),
        migrations.AlterField(
            model_name="requests",
            name="request_mode",
            field=models.CharField(db_index=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name="requests",
            name="request_priority",
            field=models.CharField(db_index=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name="requests",
            name="request_resolved_time",
            field=models.DateTimeField(blank=True, db_index=True, null=True),
        ),
        migrations.AlterField(
            model_name="requests",
            name="request_status",
            field=models.CharField(db_index=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name="requests",
            name="request_type",
            field=models.CharField(db_index=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name="requests",
            name="requester_department",
            field=models.CharField(db_index=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name="requests",
            name="requester_designation",
            field=models.CharField(db_index=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name="requests",
            name="requester_email",
            field=models.CharField(db_index=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name="requests",
            name="requester_extension",
            field=models.CharField(db_index=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name="requests",
            name="requester_name",
            field=models.CharField(db_index=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name="requests",
            name="requester_phone_number",
            field=models.CharField(db_index=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name="requests",
            name="requester_pr_number",
            field=models.CharField(db_index=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name="requests",
            name="subject",
            field=models.CharField(db_index=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name="technician",
            name="department",
            field=models.CharField(
                blank=True, db_index=True, max_length=100, null=True
            ),
        ),
        migrations.AlterField(
            model_name="technician",
            name="designation",
            field=models.CharField(
                blank=True, db_index=True, max_length=100, null=True
            ),
        ),
        migrations.AlterField(
            model_name="technician",
            name="extension_number",
            field=models.CharField(blank=True, db_index=True, max_length=10, null=True),
        ),
        migrations.AlterField(
            model_name="technician",
            name="mobile_number",
            field=models.CharField(blank=True, db_index=True, max_length=10, null=True),
        ),
        migrations.AlterField(
            model_name="technician",
            name="pr_number",
            field=models.CharField(db_index=True, max_length=100),
        ),
        migrations.CreateModel(
            name="Assest_Details",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("brand", models.CharField(db_index=True, max_length=100, null=True)),
                (
                    "model_name",
                    models.CharField(db_index=True, max_length=100, null=True),
                ),
                (
                    "model_number",
                    models.CharField(db_index=True, max_length=100, null=True),
                ),
                (
                    "serial_number",
                    models.CharField(db_index=True, max_length=100, null=True),
                ),
                (
                    "date_of_purchase",
                    models.DateTimeField(auto_now_add=True, db_index=True),
                ),
                (
                    "description",
                    models.TextField(db_index=True, max_length=99999999, null=True),
                ),
                (
                    "assest_name",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="assest_details",
                        to="HTMS_App.assets",
                    ),
                ),
                (
                    "facility",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="facilities",
                        to="HTMS_App.facilitydropdown",
                    ),
                ),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="users",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
        ),
    ]
