# Generated by Django 4.1.1 on 2023-01-25 16:15

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ("HTMS_App", "0008_rename_asset_details_assetdetails"),
    ]

    operations = [
        migrations.AlterField(
            model_name="assetdetails",
            name="asset_user",
            field=models.ForeignKey(
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="users",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
        migrations.AlterField(
            model_name="assetdetails",
            name="assign_to_ticket",
            field=models.ForeignKey(
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="assign_to_ticket",
                to="HTMS_App.requests",
            ),
        ),
    ]
