# Generated by Django 4.1.1 on 2023-02-02 13:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("HTMS_App", "0011_requests_request_closed_user"),
    ]

    operations = [
        migrations.AlterField(
            model_name="assetdetails",
            name="date_added",
            field=models.DateField(auto_now_add=True, db_index=True),
        ),
    ]
