# Generated by Django 4.1.1 on 2023-02-02 15:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("HTMS_App", "0018_alter_assetdetails_date_of_purchase"),
    ]

    operations = [
        migrations.AlterField(
            model_name="assetdetails",
            name="date_of_purchase",
            field=models.DateTimeField(db_index=True),
        ),
    ]
