# Generated by Django 4.1.1 on 2023-02-02 16:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("HTMS_App", "0019_alter_assetdetails_date_of_purchase"),
    ]

    operations = [
        migrations.CreateModel(
            name="AssetStatus",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("status_name", models.CharField(db_index=True, max_length=50)),
            ],
        ),
        migrations.AlterField(
            model_name="assetdetails",
            name="current_status",
            field=models.CharField(
                choices=[
                    ("in-stock", "In Stock"),
                    ("in-use", "In Use"),
                    ("returned-to-vendor", "Returned To Vendor"),
                    ("lost", "Lost"),
                ],
                db_index=True,
                default="in-stock",
                max_length=20,
            ),
        ),
        migrations.AlterField(
            model_name="assetdetails",
            name="date_added",
            field=models.DateTimeField(db_index=True),
        ),
    ]
