# Generated by Django 4.1.1 on 2023-02-02 16:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("HTMS_App", "0020_assetstatus_alter_assetdetails_current_status_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="assetdetails",
            name="current_status",
            field=models.CharField(db_index=True, default="in-stock", max_length=50),
        ),
    ]
