# Generated by Django 4.1.1 on 2023-02-04 17:11

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ("HTMS_App", "0023_alter_assetdetails_asset_name_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="requests",
            name="request_closed_user",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="request_closed_user",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
    ]
