# Generated by Django 4.1.1 on 2023-02-04 18:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("HTMS_App", "0026_alter_requests_last_modified_by_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="technician",
            name="facility",
            field=models.ManyToManyField(
                blank=True, db_index=True, to="HTMS_App.facilitydropdown"
            ),
        ),
    ]
