# Generated by Django 4.1.1 on 2023-02-09 12:36

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("HTMS_App", "0027_alter_technician_facility"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="requests",
            name="request_completion_date",
        ),
    ]
