# Generated by Django 4.1.1 on 2023-02-09 15:46

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("HTMS_App", "0028_remove_requests_request_completion_date"),
    ]

    operations = [
        migrations.CreateModel(
            name="Location",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "location_name",
                    models.CharField(
                        blank=True, db_index=True, max_length=100, null=True
                    ),
                ),
                (
                    "location_floor",
                    models.CharField(
                        blank=True, db_index=True, max_length=100, null=True
                    ),
                ),
            ],
        ),
        migrations.AddField(
            model_name="assetdetails",
            name="location",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="location",
                to="HTMS_App.location",
            ),
        ),
    ]
