# Generated by Django 4.1.7 on 2023-02-19 12:23

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("HTMS_App", "0030_remove_assetdetails_location_requests_location"),
    ]

    operations = [
        migrations.AddField(
            model_name="assetdetails",
            name="expiration_date",
            field=models.DateTimeField(blank=True, db_index=True, null=True),
        ),
    ]
