# Generated by Django 4.1.7 on 2023-02-20 10:53

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("HTMS_App", "0032_assetdetails_added_by"),
    ]

    operations = [
        migrations.AlterField(
            model_name="assetdetails",
            name="date_of_purchase",
            field=models.DateTimeField(blank=True, db_index=True, null=True),
        ),
    ]
