# Generated by Django 4.1.7 on 2023-02-20 17:32

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("HTMS_App", "0034_alter_assetdetails_facility"),
    ]

    operations = [
        migrations.AlterField(
            model_name="technician",
            name="mobile_number",
            field=models.CharField(blank=True, db_index=True, max_length=50, null=True),
        ),
    ]
