services:
  app:
    build: .
    image: htms_docker_image
    container_name: htms_docker_container
    command: gunicorn --workers 3 --timeout 86400 --bind 0.0.0.0:8003 HTMS_Website.wsgi:application
    ports:
      - 8003:8003
    volumes:
      - .:/htms_website
  #   depends_on:
  #     - node

  # node:
  #   image: node:alpine
  #   ports:
  #     - "3000:3000"

  #   volumes:
  #     - .:/htms_website

  #   working_dir: /htms_website/HTMS_App/static/HTMS_App/js

  #   command: sh -c "npm install && npm run start"
