
services:
  app:
    build: .
    restart: always
    image: htms_docker_image
    container_name: htms_docker_container
    # command: gunicorn --workers 3 --timeout 86400 --bind 0.0.0.0:8004 HTMS_Website.wsgi:application
    volumes:
      - .:/htms_website/
      - ./static:/htms_website/static


  nginx:
    build: 
      context: ./nginx
    image: htms_nginx_image
    container_name: htms_nginx_container
    restart: always
    ports:
      - 8004:8004
    volumes:
      - ./static:/htms_website/static





  #   depends_on:
  #     - node

  # node:
  #   image: node:alpine
  #   ports:
  #     - "3000:3000"

  #   volumes:
  #     - .:/htms_website
 
  #   working_dir: /htms_website/HTMS_App/static/HTMS_App/js

  #   command: sh -c "npm install && npm run start"
